apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener-ansible-pipeline
  namespace: ansible-pipeline-namespace
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: ClusterTriggerBinding
          ref: github-pullreq
      template:
        ref: trigger-template-ansible-pipeline
