apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ansible-pipeline
  namespace: ansible-pipeline-namespace
spec:
  params:
    - description: Git Repository
      name: git-repo-url
      type: string
    - description: Ansible Url
      name: ansible-url
      type: string
    - description: Ansible Access Token
      name: ansible-token
      type: string
    - description: Git Branch
      name: git-branch
      type: string
    - default: /workspace/shared-data/job_vars.json
      description: Job Vars
      name: job-extra-vars-path
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.git-repo-url)
        - name: refspec
          value: $(params.git-branch)
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.40.2
        - name: userHome
          value: /home/git
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-pvc
    - name: ansible-launch-task
      params:
        - name: ansible_url
          value: $(params.ansible-url)
        - name: ansible_token
          value: $(params.ansible-token)
        - name: job_vars_path
          value: $(params.job-extra-vars-path)
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: ansible-launch-task
      workspaces:
        - name: shared-data
          workspace: pipeline-pvc
  workspaces:
    - name: pipeline-pvc
